/*
Rode este bloco depois de popular #MEU_SALARIO_COMPOSTO no script diagnostico.
Objetivo: medir o impacto de ativar a regra de marco em FINANCEIRO_BASE que troca PFHSTSAL por SC_FIN/PFFINANC.

Ele mostra, para cada linha FINANCEIRO:
- se o ORIGINAL bate com o resultado atual (#MEU), com PFHSTSAL, com PFFINANC ou com SC_FIN;
- se ativar SC_FIN/PFFINANC AJUDA, QUEBRA, ou e NEUTRO.
*/

DECLARE @TOL_VALOR_HORA   decimal(19,6) = 0.005;
DECLARE @TOL_VALOR_MENSAL decimal(19,6) = 0.015;

;WITH
MEU_FIN AS
(
    SELECT
        CODFILIAL = CAST(M.CODFILIAL AS smallint),
        CHAPA = CAST(M.CHAPA AS varchar(16)),
        CODEVENTO = CAST(M.CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(M.COMPETENCIA AS date),
        M_VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(M.VALOR_HORA AS varchar(50)), ',', '.')),
        M_VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(M.VALOR_MENSAL AS varchar(50)), ',', '.')),
        M_JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(M.JORNADA_MENSAL AS varchar(50)), ',', '.')),
        M.FONTE_DEBUG
    FROM #MEU_SALARIO_COMPOSTO M
    WHERE M.FONTE_DEBUG = 'FINANCEIRO'
      AND CAST(M.COMPETENCIA AS date) = @COMPETENCIA
),
ORI AS
(
    SELECT
        CODFILIAL = CAST(O.CODFILIAL AS smallint),
        CHAPA = CAST(O.CHAPA AS varchar(16)),
        CODEVENTO = CAST(O.CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(O.COMPETENCIA AS date),
        O_VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.VALOR_HORA AS varchar(50)), ',', '.')),
        O_VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.VALOR_MENSAL AS varchar(50)), ',', '.')),
        O_JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.JORNADA_MENSAL AS varchar(50)), ',', '.'))
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] O WITH (NOLOCK)
    WHERE CAST(O.COMPETENCIA AS date) = @COMPETENCIA
),
PS_RN AS
(
    SELECT
        PS.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY PS.CODCOLIGADA, PS.CHAPA, PS.CODEVENTO
            ORDER BY CASE WHEN PS.NROPERIODO = 40 THEN 0 WHEN PS.NROPERIODO = 10 THEN 1 ELSE 2 END,
                     PS.RECMODIFIEDON DESC,
                     PS.RECCREATEDON DESC
        )
    FROM PFFINANC PS WITH (NOLOCK)
    JOIN MEU_FIN M
      ON M.CHAPA = PS.CHAPA
     AND M.CODEVENTO = PS.CODEVENTO
    WHERE PS.CODCOLIGADA = @CODCOLIGADA
      AND PS.MESCOMP = @MES
      AND PS.ANOCOMP = @ANO
      AND PS.NROPERIODO IN (10, 40)
),
H_EVENTO AS
(
    SELECT
        H.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO
            ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC
        )
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN MEU_FIN M
      ON M.CHAPA = H.CHAPA
     AND M.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA
      AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
BASE AS
(
    SELECT
        M.CODFILIAL,
        M.CHAPA,
        M.CODEVENTO,
        PF.NOME,
        M.M_VALOR_HORA,
        M.M_VALOR_MENSAL,
        M.M_JORNADA_MENSAL,
        O.O_VALOR_HORA,
        O.O_VALOR_MENSAL,
        O.O_JORNADA_MENSAL,

        PS_NROPERIODO = PS.NROPERIODO,
        PS_REF = PS.REF,
        PS_VALOR = PS.VALOR,
        PS_VALORORIGINAL = PS.VALORORIGINAL,
        PS_MENSAL = CAST(COALESCE(PS.VALORORIGINAL, PS.VALOR) AS decimal(19,6)),
        PS_HORA = CAST(CASE WHEN ISNULL(PS.REF,0) > 0 THEN COALESCE(PS.VALORORIGINAL, PS.VALOR) / PS.REF ELSE NULL END AS decimal(19,6)),
        PS_JORNADA = CAST(PS.REF AS decimal(19,6)),
        PS_RECCREATEDON = PS.RECCREATEDON,
        PS_RECMODIFIEDON = PS.RECMODIFIEDON,

        H_NROSALARIO = H.NROSALARIO,
        H_DTMUDANCA = H.DTMUDANCA,
        H_MENSAL = CAST(H.SALARIO AS decimal(19,6)),
        H_JORNADA = CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.JORNADA / 60.0 ELSE NULL END AS decimal(19,6)),
        H_HORA = CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.SALARIO / (H.JORNADA / 60.0) ELSE H.SALARIO END AS decimal(19,6)),
        H_RECMODIFIEDON = H.RECMODIFIEDON,

        SC_MENSAL = CAST(SC.VALOR AS decimal(19,6)),
        SC_JORNADA = CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.JORNADA / 60.0 ELSE NULL END AS decimal(19,6)),
        SC_HORA = CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.VALOR / (SC.JORNADA / 60.0) ELSE SC.VALOR END AS decimal(19,6)),
        SC_RECCREATEDON = SC.RECCREATEDON,
        SC_RECMODIFIEDON = SC.RECMODIFIEDON
    FROM MEU_FIN M
    LEFT JOIN ORI O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
    LEFT JOIN PFUNC PF WITH (NOLOCK)
      ON PF.CODCOLIGADA = @CODCOLIGADA
     AND PF.CHAPA = M.CHAPA
    LEFT JOIN PS_RN PS
      ON PS.CHAPA = M.CHAPA
     AND PS.CODEVENTO = M.CODEVENTO
     AND PS.RN = 1
    LEFT JOIN H_EVENTO H
      ON H.CHAPA = M.CHAPA
     AND H.CODEVENTO = M.CODEVENTO
     AND H.RN = 1
    OUTER APPLY
    (
        SELECT TOP (1)
            SC.VALOR,
            SC.JORNADA,
            SC.RECCREATEDON,
            SC.RECMODIFIEDON
        FROM PFSALCMP SC WITH (NOLOCK)
        WHERE SC.CODCOLIGADA = @CODCOLIGADA
          AND SC.CHAPA = M.CHAPA
          AND SC.CODEVENTO = M.CODEVENTO
          AND SC.NROSALARIO = H.NROSALARIO
        ORDER BY SC.RECMODIFIEDON DESC, SC.RECCREATEDON DESC
    ) SC
),
SCORED AS
(
    SELECT
        B.*,
        MATCH_MEU = CASE WHEN ABS(ISNULL(B.M_VALOR_HORA,0) - ISNULL(B.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
                          AND ABS(ISNULL(B.M_VALOR_MENSAL,0) - ISNULL(B.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        MATCH_PS = CASE WHEN ABS(ISNULL(B.PS_HORA,0) - ISNULL(B.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
                         AND ABS(ISNULL(B.PS_MENSAL,0) - ISNULL(B.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        MATCH_H = CASE WHEN ABS(ISNULL(B.H_HORA,0) - ISNULL(B.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
                        AND ABS(ISNULL(B.H_MENSAL,0) - ISNULL(B.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        MATCH_SC = CASE WHEN ABS(ISNULL(B.SC_HORA,0) - ISNULL(B.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
                         AND ABS(ISNULL(B.SC_MENSAL,0) - ISNULL(B.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        SC_MATCHES_PS = CASE WHEN ABS(ISNULL(B.SC_HORA,0) - ISNULL(B.PS_HORA,0)) <= @TOL_VALOR_HORA
                              AND ABS(ISNULL(B.SC_MENSAL,0) - ISNULL(B.PS_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END
    FROM BASE B
)
SELECT
    IMPACTO_ATIVAR_SCFIN = CASE
        WHEN MATCH_MEU = 1 AND MATCH_SC = 1 THEN 'NEUTRO_JA_BATE'
        WHEN MATCH_MEU = 0 AND MATCH_SC = 1 THEN 'AJUDA_USAR_SCFIN'
        WHEN MATCH_MEU = 1 AND MATCH_SC = 0 AND SC_RECMODIFIEDON IS NOT NULL THEN 'QUEBRA_SE_USAR_SCFIN'
        WHEN MATCH_MEU = 0 AND MATCH_PS = 1 THEN 'AJUDA_USAR_PS_MAS_NAO_SC'
        WHEN O_VALOR_MENSAL IS NULL THEN 'SEM_ORIGINAL'
        ELSE 'NAO_RESOLVE'
    END,
    *
FROM SCORED
WHERE O_VALOR_MENSAL IS NULL
   OR MATCH_MEU = 0
   OR (MATCH_MEU = 1 AND SC_RECMODIFIEDON IS NOT NULL AND MATCH_SC = 0)
ORDER BY IMPACTO_ATIVAR_SCFIN, CODFILIAL, CHAPA, CODEVENTO;

SELECT
    IMPACTO_ATIVAR_SCFIN = CASE
        WHEN MATCH_MEU = 1 AND MATCH_SC = 1 THEN 'NEUTRO_JA_BATE'
        WHEN MATCH_MEU = 0 AND MATCH_SC = 1 THEN 'AJUDA_USAR_SCFIN'
        WHEN MATCH_MEU = 1 AND MATCH_SC = 0 AND SC_RECMODIFIEDON IS NOT NULL THEN 'QUEBRA_SE_USAR_SCFIN'
        WHEN MATCH_MEU = 0 AND MATCH_PS = 1 THEN 'AJUDA_USAR_PS_MAS_NAO_SC'
        WHEN O_VALOR_MENSAL IS NULL THEN 'SEM_ORIGINAL'
        ELSE 'NAO_RESOLVE'
    END,
    QTD = COUNT(*)
FROM SCORED
WHERE O_VALOR_MENSAL IS NULL
   OR MATCH_MEU = 0
   OR (MATCH_MEU = 1 AND SC_RECMODIFIEDON IS NOT NULL AND MATCH_SC = 0)
GROUP BY CASE
        WHEN MATCH_MEU = 1 AND MATCH_SC = 1 THEN 'NEUTRO_JA_BATE'
        WHEN MATCH_MEU = 0 AND MATCH_SC = 1 THEN 'AJUDA_USAR_SCFIN'
        WHEN MATCH_MEU = 1 AND MATCH_SC = 0 AND SC_RECMODIFIEDON IS NOT NULL THEN 'QUEBRA_SE_USAR_SCFIN'
        WHEN MATCH_MEU = 0 AND MATCH_PS = 1 THEN 'AJUDA_USAR_PS_MAS_NAO_SC'
        WHEN O_VALOR_MENSAL IS NULL THEN 'SEM_ORIGINAL'
        ELSE 'NAO_RESOLVE'
    END
ORDER BY QTD DESC;
