/*
Rode este bloco logo depois de popular #MEU_SALARIO_COMPOSTO.
Objetivo: para cada chave divergente, comparar o ORIGINAL da AIN contra fontes candidatas
(PFFINANC, PFHSTSAL, PFSALCMP, PFATIVREMUNERADA) e mostrar qual fonte bate em valor hora/mensal.
*/

DECLARE @TOL_VALOR_HORA   decimal(19,6) = 0.005;
DECLARE @TOL_VALOR_MENSAL decimal(19,6) = 0.015;

;WITH
MEU AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.')),
        FONTE_DEBUG,
        SALARIO_DEBUG,
        JORNADA_DEBUG
    FROM #MEU_SALARIO_COMPOSTO
),
ORI AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.'))
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] WITH (NOLOCK)
    WHERE CAST(COMPETENCIA AS date) = @COMPETENCIA
),
CHAVES AS
(
    SELECT
        CODFILIAL = COALESCE(M.CODFILIAL, O.CODFILIAL),
        CHAPA = COALESCE(M.CHAPA, O.CHAPA),
        CODEVENTO = COALESCE(M.CODEVENTO, O.CODEVENTO),
        COMPETENCIA = COALESCE(M.COMPETENCIA, O.COMPETENCIA),
        M_VALOR_HORA = M.VALOR_HORA,
        O_VALOR_HORA = O.VALOR_HORA,
        M_VALOR_MENSAL = M.VALOR_MENSAL,
        O_VALOR_MENSAL = O.VALOR_MENSAL,
        M_JORNADA_MENSAL = M.JORNADA_MENSAL,
        O_JORNADA_MENSAL = O.JORNADA_MENSAL,
        M_FONTE = M.FONTE_DEBUG,
        M_SALARIO_DEBUG = M.SALARIO_DEBUG,
        M_JORNADA_DEBUG = M.JORNADA_DEBUG
    FROM MEU M
    FULL OUTER JOIN ORI O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
    WHERE O.CHAPA IS NULL
       OR M.CHAPA IS NULL
       OR ABS(ISNULL(M.VALOR_HORA,0) - ISNULL(O.VALOR_HORA,0)) > @TOL_VALOR_HORA
       OR ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) > @TOL_VALOR_MENSAL
),
PS AS
(
    SELECT
        PS.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY PS.CODCOLIGADA, PS.CHAPA, PS.CODEVENTO
            ORDER BY CASE WHEN PS.NROPERIODO = 40 THEN 0 WHEN PS.NROPERIODO = 10 THEN 1 ELSE 2 END,
                     PS.RECMODIFIEDON DESC,
                     PS.RECCREATEDON DESC
        )
    FROM PFFINANC PS WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = PS.CHAPA AND C.CODEVENTO = PS.CODEVENTO
    WHERE PS.CODCOLIGADA = @CODCOLIGADA
      AND PS.MESCOMP = @MES
      AND PS.ANOCOMP = @ANO
      AND PS.NROPERIODO IN (10, 40)
),
H_EVENTO AS
(
    SELECT
        H.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO
            ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC
        )
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = H.CHAPA AND C.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA
      AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
SC AS
(
    SELECT
        SC.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY SC.CODCOLIGADA, SC.CHAPA, SC.CODEVENTO, SC.NROSALARIO
            ORDER BY SC.RECMODIFIEDON DESC, SC.RECCREATEDON DESC
        )
    FROM PFSALCMP SC WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = SC.CHAPA AND C.CODEVENTO = SC.CODEVENTO
    WHERE SC.CODCOLIGADA = @CODCOLIGADA
      AND SC.RECCREATEDON < @PROXIMO_DIA_COMPETENCIA
),
AR AS
(
    SELECT
        AR.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY AR.CODCOLIGADA, AR.CHAPA, AR.CODEVENTO
            ORDER BY AR.RECMODIFIEDON DESC, AR.RECCREATEDON DESC
        )
    FROM PFATIVREMUNERADA AR WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = AR.CHAPA AND C.CODEVENTO = AR.CODEVENTO
    WHERE AR.CODCOLIGADA = @CODCOLIGADA
      AND AR.RECMODIFIEDON < @PROXIMO_DIA_COMPETENCIA
),
CANDIDATOS AS
(
    SELECT
        C.CODFILIAL, C.CHAPA, C.CODEVENTO,
        FONTE_CANDIDATA = CAST('MEU_FINAL' AS varchar(40)),
        CAND_VALOR_MENSAL = CAST(C.M_VALOR_MENSAL AS decimal(19,6)),
        CAND_JORNADA_MENSAL = CAST(C.M_JORNADA_MENSAL AS decimal(19,6)),
        CAND_VALOR_HORA = CAST(C.M_VALOR_HORA AS decimal(19,6)),
        INFO = CAST(C.M_FONTE AS varchar(200))
    FROM CHAVES C

    UNION ALL
    SELECT
        C.CODFILIAL, C.CHAPA, C.CODEVENTO,
        'PFFINANC_VALOR_REF',
        CAST(COALESCE(PS.VALORORIGINAL, PS.VALOR) AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(PS.REF,0) > 0 THEN PS.REF ELSE NULL END AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(PS.REF,0) > 0 THEN COALESCE(PS.VALORORIGINAL, PS.VALOR) / PS.REF ELSE NULL END AS decimal(19,6)),
        CAST(CONCAT('NROPERIODO=', PS.NROPERIODO, '; REF=', PS.REF, '; VALOR=', PS.VALOR, '; VALORORIGINAL=', PS.VALORORIGINAL) AS varchar(200))
    FROM CHAVES C
    JOIN PS ON PS.CHAPA = C.CHAPA AND PS.CODEVENTO = C.CODEVENTO AND PS.RN = 1

    UNION ALL
    SELECT
        C.CODFILIAL, C.CHAPA, C.CODEVENTO,
        'PFHSTSAL_ULT_EVENTO',
        CAST(H.SALARIO AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.JORNADA / 60.0 ELSE NULL END AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.SALARIO / (H.JORNADA / 60.0) ELSE H.SALARIO END AS decimal(19,6)),
        CAST(CONCAT('NROSALARIO=', H.NROSALARIO, '; DTMUDANCA=', CONVERT(varchar(30), H.DTMUDANCA, 120), '; RECMODIFIEDON=', CONVERT(varchar(30), H.RECMODIFIEDON, 120)) AS varchar(200))
    FROM CHAVES C
    JOIN H_EVENTO H ON H.CHAPA = C.CHAPA AND H.CODEVENTO = C.CODEVENTO AND H.RN = 1

    UNION ALL
    SELECT
        C.CODFILIAL, C.CHAPA, C.CODEVENTO,
        'PFSALCMP_DO_HIST',
        CAST(SC.VALOR AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.JORNADA / 60.0 ELSE NULL END AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.VALOR / (SC.JORNADA / 60.0) ELSE SC.VALOR END AS decimal(19,6)),
        CAST(CONCAT('NROSALARIO=', SC.NROSALARIO, '; RECCREATEDON=', CONVERT(varchar(30), SC.RECCREATEDON, 120), '; RECMODIFIEDON=', CONVERT(varchar(30), SC.RECMODIFIEDON, 120)) AS varchar(200))
    FROM CHAVES C
    JOIN H_EVENTO H ON H.CHAPA = C.CHAPA AND H.CODEVENTO = C.CODEVENTO AND H.RN = 1
    JOIN SC ON SC.CHAPA = C.CHAPA AND SC.CODEVENTO = C.CODEVENTO AND SC.NROSALARIO = H.NROSALARIO AND SC.RN = 1

    UNION ALL
    SELECT
        C.CODFILIAL, C.CHAPA, C.CODEVENTO,
        'PFATIVREMUNERADA_ULT',
        CAST(AR.VALOR AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(AR.JORNADA,0) > 0 THEN AR.JORNADA / 60.0 ELSE NULL END AS decimal(19,6)),
        CAST(CASE WHEN ISNULL(AR.JORNADA,0) > 0 THEN AR.VALOR / (AR.JORNADA / 60.0) ELSE AR.VALOR END AS decimal(19,6)),
        CAST(CONCAT('RECCREATEDON=', CONVERT(varchar(30), AR.RECCREATEDON, 120), '; RECMODIFIEDON=', CONVERT(varchar(30), AR.RECMODIFIEDON, 120)) AS varchar(200))
    FROM CHAVES C
    JOIN AR ON AR.CHAPA = C.CHAPA AND AR.CODEVENTO = C.CODEVENTO AND AR.RN = 1
),
SCORED AS
(
    SELECT
        C.CODFILIAL,
        C.CHAPA,
        C.CODEVENTO,
        PF.NOME,
        C.M_FONTE,
        C.O_VALOR_HORA,
        C.O_VALOR_MENSAL,
        C.O_JORNADA_MENSAL,
        C.M_VALOR_HORA,
        C.M_VALOR_MENSAL,
        C.M_JORNADA_MENSAL,
        K.FONTE_CANDIDATA,
        K.CAND_VALOR_HORA,
        K.CAND_VALOR_MENSAL,
        K.CAND_JORNADA_MENSAL,
        MATCH_VALOR_HORA = CASE WHEN ABS(ISNULL(K.CAND_VALOR_HORA,0) - ISNULL(C.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA THEN 1 ELSE 0 END,
        MATCH_VALOR_MENSAL = CASE WHEN ABS(ISNULL(K.CAND_VALOR_MENSAL,0) - ISNULL(C.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        MATCH_AMBOS = CASE
            WHEN ABS(ISNULL(K.CAND_VALOR_HORA,0) - ISNULL(C.O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
             AND ABS(ISNULL(K.CAND_VALOR_MENSAL,0) - ISNULL(C.O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END,
        SCORE_ABS =
            ABS(ISNULL(K.CAND_VALOR_HORA,0) - ISNULL(C.O_VALOR_HORA,0))
          + ABS(ISNULL(K.CAND_VALOR_MENSAL,0) - ISNULL(C.O_VALOR_MENSAL,0)),
        K.INFO
    FROM CHAVES C
    JOIN CANDIDATOS K
      ON K.CODFILIAL = C.CODFILIAL
     AND K.CHAPA = C.CHAPA
     AND K.CODEVENTO = C.CODEVENTO
    LEFT JOIN PFUNC PF WITH (NOLOCK)
      ON PF.CODCOLIGADA = @CODCOLIGADA
     AND PF.CHAPA = C.CHAPA
)
SELECT *
FROM SCORED
ORDER BY CODFILIAL, CHAPA, CODEVENTO, MATCH_AMBOS DESC, SCORE_ABS, FONTE_CANDIDATA;

-- Resumo: qual fonte candidata bate exatamente com o original?
;WITH
MEU AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        FONTE_DEBUG
    FROM #MEU_SALARIO_COMPOSTO
),
ORI AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.'))
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] WITH (NOLOCK)
    WHERE CAST(COMPETENCIA AS date) = @COMPETENCIA
),
CHAVES AS
(
    SELECT
        CODFILIAL = COALESCE(M.CODFILIAL, O.CODFILIAL),
        CHAPA = COALESCE(M.CHAPA, O.CHAPA),
        CODEVENTO = COALESCE(M.CODEVENTO, O.CODEVENTO),
        O_VALOR_HORA = O.VALOR_HORA,
        O_VALOR_MENSAL = O.VALOR_MENSAL,
        M_FONTE = M.FONTE_DEBUG
    FROM MEU M
    FULL OUTER JOIN ORI O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
    WHERE O.CHAPA IS NOT NULL
      AND M.CHAPA IS NOT NULL
      AND (
          ABS(ISNULL(M.VALOR_HORA,0) - ISNULL(O.VALOR_HORA,0)) > @TOL_VALOR_HORA
       OR ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) > @TOL_VALOR_MENSAL
      )
),
PS AS
(
    SELECT PS.*, RN = ROW_NUMBER() OVER (PARTITION BY PS.CODCOLIGADA, PS.CHAPA, PS.CODEVENTO ORDER BY CASE WHEN PS.NROPERIODO = 40 THEN 0 WHEN PS.NROPERIODO = 10 THEN 1 ELSE 2 END, PS.RECMODIFIEDON DESC, PS.RECCREATEDON DESC)
    FROM PFFINANC PS WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = PS.CHAPA AND C.CODEVENTO = PS.CODEVENTO
    WHERE PS.CODCOLIGADA = @CODCOLIGADA AND PS.MESCOMP = @MES AND PS.ANOCOMP = @ANO AND PS.NROPERIODO IN (10, 40)
),
H_EVENTO AS
(
    SELECT H.*, RN = ROW_NUMBER() OVER (PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC)
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = H.CHAPA AND C.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
SC AS
(
    SELECT SC.*, RN = ROW_NUMBER() OVER (PARTITION BY SC.CODCOLIGADA, SC.CHAPA, SC.CODEVENTO, SC.NROSALARIO ORDER BY SC.RECMODIFIEDON DESC, SC.RECCREATEDON DESC)
    FROM PFSALCMP SC WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = SC.CHAPA AND C.CODEVENTO = SC.CODEVENTO
    WHERE SC.CODCOLIGADA = @CODCOLIGADA AND SC.RECCREATEDON < @PROXIMO_DIA_COMPETENCIA
),
CANDIDATOS AS
(
    SELECT C.CODFILIAL, C.CHAPA, C.CODEVENTO, C.M_FONTE, C.O_VALOR_HORA, C.O_VALOR_MENSAL, 'PFFINANC_VALOR_REF' FONTE_CANDIDATA,
           CAST(COALESCE(PS.VALORORIGINAL, PS.VALOR) AS decimal(19,6)) CAND_VALOR_MENSAL,
           CAST(CASE WHEN ISNULL(PS.REF,0) > 0 THEN COALESCE(PS.VALORORIGINAL, PS.VALOR) / PS.REF ELSE NULL END AS decimal(19,6)) CAND_VALOR_HORA
    FROM CHAVES C JOIN PS ON PS.CHAPA = C.CHAPA AND PS.CODEVENTO = C.CODEVENTO AND PS.RN = 1
    UNION ALL
    SELECT C.CODFILIAL, C.CHAPA, C.CODEVENTO, C.M_FONTE, C.O_VALOR_HORA, C.O_VALOR_MENSAL, 'PFHSTSAL_ULT_EVENTO',
           CAST(H.SALARIO AS decimal(19,6)),
           CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.SALARIO / (H.JORNADA / 60.0) ELSE H.SALARIO END AS decimal(19,6))
    FROM CHAVES C JOIN H_EVENTO H ON H.CHAPA = C.CHAPA AND H.CODEVENTO = C.CODEVENTO AND H.RN = 1
    UNION ALL
    SELECT C.CODFILIAL, C.CHAPA, C.CODEVENTO, C.M_FONTE, C.O_VALOR_HORA, C.O_VALOR_MENSAL, 'PFSALCMP_DO_HIST',
           CAST(SC.VALOR AS decimal(19,6)),
           CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.VALOR / (SC.JORNADA / 60.0) ELSE SC.VALOR END AS decimal(19,6))
    FROM CHAVES C
    JOIN H_EVENTO H ON H.CHAPA = C.CHAPA AND H.CODEVENTO = C.CODEVENTO AND H.RN = 1
    JOIN SC ON SC.CHAPA = C.CHAPA AND SC.CODEVENTO = C.CODEVENTO AND SC.NROSALARIO = H.NROSALARIO AND SC.RN = 1
)
SELECT
    M_FONTE,
    FONTE_CANDIDATA,
    QTD_MATCH_AMBOS = SUM(CASE WHEN ABS(ISNULL(CAND_VALOR_HORA,0) - ISNULL(O_VALOR_HORA,0)) <= @TOL_VALOR_HORA
                                AND ABS(ISNULL(CAND_VALOR_MENSAL,0) - ISNULL(O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END),
    QTD_MATCH_HORA = SUM(CASE WHEN ABS(ISNULL(CAND_VALOR_HORA,0) - ISNULL(O_VALOR_HORA,0)) <= @TOL_VALOR_HORA THEN 1 ELSE 0 END),
    QTD_MATCH_MENSAL = SUM(CASE WHEN ABS(ISNULL(CAND_VALOR_MENSAL,0) - ISNULL(O_VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN 1 ELSE 0 END),
    QTD_CANDIDATOS = COUNT(*)
FROM CANDIDATOS
GROUP BY M_FONTE, FONTE_CANDIDATA
ORDER BY QTD_MATCH_AMBOS DESC, QTD_MATCH_MENSAL DESC, QTD_MATCH_HORA DESC, M_FONTE, FONTE_CANDIDATA;
