/*
Rode este bloco logo depois de popular #MEU_SALARIO_COMPOSTO no script diagnostico.
Ele classifica as divergencias por padrao e identifica casos de realocacao entre eventos.
*/

DECLARE @TOL_VALOR_HORA   decimal(19,6) = 0.005;
DECLARE @TOL_VALOR_MENSAL decimal(19,6) = 0.015; -- 0,01 de money/rounding entra como arredondamento

;WITH
MEU_RAW AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.')),
        FONTE_DEBUG
    FROM #MEU_SALARIO_COMPOSTO
),
ORI_RAW AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.'))
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] WITH (NOLOCK)
    WHERE CAST(COMPETENCIA AS date) = @COMPETENCIA
),
MEU AS
(
    SELECT
        CODFILIAL, CHAPA, CODEVENTO, COMPETENCIA,
        QTD_MEU = COUNT(*),
        VALOR_HORA_MEU = SUM(VALOR_HORA),
        VALOR_MENSAL_MEU = SUM(VALOR_MENSAL),
        JORNADA_MENSAL_MEU = SUM(JORNADA_MENSAL),
        FONTES_MEU = STRING_AGG(CAST(FONTE_DEBUG AS varchar(max)), ',')
    FROM MEU_RAW
    GROUP BY CODFILIAL, CHAPA, CODEVENTO, COMPETENCIA
),
ORI AS
(
    SELECT
        CODFILIAL, CHAPA, CODEVENTO, COMPETENCIA,
        QTD_ORIGINAL = COUNT(*),
        VALOR_HORA_ORIGINAL = SUM(VALOR_HORA),
        VALOR_MENSAL_ORIGINAL = SUM(VALOR_MENSAL),
        JORNADA_MENSAL_ORIGINAL = SUM(JORNADA_MENSAL)
    FROM ORI_RAW
    GROUP BY CODFILIAL, CHAPA, CODEVENTO, COMPETENCIA
),
D AS
(
    SELECT
        CODFILIAL = COALESCE(M.CODFILIAL, O.CODFILIAL),
        CHAPA = COALESCE(M.CHAPA, O.CHAPA),
        CODEVENTO = COALESCE(M.CODEVENTO, O.CODEVENTO),
        COMPETENCIA = COALESCE(M.COMPETENCIA, O.COMPETENCIA),
        M.QTD_MEU,
        O.QTD_ORIGINAL,
        M.VALOR_HORA_MEU,
        O.VALOR_HORA_ORIGINAL,
        DIFF_VALOR_HORA = CAST(ISNULL(M.VALOR_HORA_MEU, 0) - ISNULL(O.VALOR_HORA_ORIGINAL, 0) AS decimal(19,6)),
        M.VALOR_MENSAL_MEU,
        O.VALOR_MENSAL_ORIGINAL,
        DIFF_VALOR_MENSAL = CAST(ISNULL(M.VALOR_MENSAL_MEU, 0) - ISNULL(O.VALOR_MENSAL_ORIGINAL, 0) AS decimal(19,6)),
        M.JORNADA_MENSAL_MEU,
        O.JORNADA_MENSAL_ORIGINAL,
        DIFF_JORNADA_MENSAL = CAST(ISNULL(M.JORNADA_MENSAL_MEU, 0) - ISNULL(O.JORNADA_MENSAL_ORIGINAL, 0) AS decimal(19,6)),
        M.FONTES_MEU,
        CLASSE = CASE
            WHEN O.CHAPA IS NULL THEN N'SÓ_NO_MEU'
            WHEN M.CHAPA IS NULL THEN N'SÓ_NO_ORIGINAL'
            WHEN ISNULL(M.QTD_MEU,0) <> ISNULL(O.QTD_ORIGINAL,0) THEN N'DUPLICIDADE'
            WHEN ABS(ISNULL(M.VALOR_MENSAL_MEU,0) - ISNULL(O.VALOR_MENSAL_ORIGINAL,0)) <= @TOL_VALOR_MENSAL
             AND ABS(ISNULL(M.VALOR_HORA_MEU,0) - ISNULL(O.VALOR_HORA_ORIGINAL,0)) <= @TOL_VALOR_HORA THEN N'OK_TOLERANCIA'
            WHEN ABS(ISNULL(M.VALOR_MENSAL_MEU,0) - ISNULL(O.VALOR_MENSAL_ORIGINAL,0)) <= @TOL_VALOR_MENSAL THEN N'MESMO_MENSAL_DIF_VALOR_HORA'
            WHEN ABS(ISNULL(M.VALOR_HORA_MEU,0) - ISNULL(O.VALOR_HORA_ORIGINAL,0)) <= @TOL_VALOR_HORA THEN N'MESMO_VALOR_HORA_DIF_JORNADA'
            ELSE N'VALOR_HORA_E_MENSAL_DIFERENTES'
        END
    FROM MEU M
    FULL OUTER JOIN ORI O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
)
SELECT CLASSE, FONTES_MEU, QTD = COUNT(*)
FROM D
WHERE CLASSE <> N'OK_TOLERANCIA'
GROUP BY CLASSE, FONTES_MEU
ORDER BY QTD DESC, CLASSE, FONTES_MEU;

;WITH
MEU_RAW AS
(
    SELECT CAST(CODFILIAL AS smallint) CODFILIAL, CAST(CHAPA AS varchar(16)) CHAPA, CAST(CODEVENTO AS varchar(10)) CODEVENTO,
           CAST(COMPETENCIA AS date) COMPETENCIA,
           TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')) VALOR_MENSAL,
           TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')) VALOR_HORA
    FROM #MEU_SALARIO_COMPOSTO
),
ORI_RAW AS
(
    SELECT CAST(CODFILIAL AS smallint) CODFILIAL, CAST(CHAPA AS varchar(16)) CHAPA, CAST(CODEVENTO AS varchar(10)) CODEVENTO,
           CAST(COMPETENCIA AS date) COMPETENCIA,
           TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')) VALOR_MENSAL,
           TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')) VALOR_HORA
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] WITH (NOLOCK)
    WHERE CAST(COMPETENCIA AS date) = @COMPETENCIA
),
D_EVENTO AS
(
    SELECT
        COALESCE(M.CODFILIAL,O.CODFILIAL) CODFILIAL,
        COALESCE(M.CHAPA,O.CHAPA) CHAPA,
        COALESCE(M.CODEVENTO,O.CODEVENTO) CODEVENTO,
        ISNULL(M.VALOR_MENSAL,0) VALOR_MENSAL_MEU,
        ISNULL(O.VALOR_MENSAL,0) VALOR_MENSAL_ORIGINAL,
        ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0) DIFF_VALOR_MENSAL
    FROM MEU_RAW M
    FULL OUTER JOIN ORI_RAW O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
    WHERE ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) > @TOL_VALOR_MENSAL
),
D_CHAPA AS
(
    SELECT
        CODFILIAL, CHAPA,
        QTD_EVENTOS_DIVERGENTES = COUNT(*),
        TOTAL_MEU = SUM(VALOR_MENSAL_MEU),
        TOTAL_ORIGINAL = SUM(VALOR_MENSAL_ORIGINAL),
        DIFF_TOTAL = SUM(DIFF_VALOR_MENSAL)
    FROM D_EVENTO
    GROUP BY CODFILIAL, CHAPA
)
SELECT
    C.CODFILIAL,
    C.CHAPA,
    C.QTD_EVENTOS_DIVERGENTES,
    C.TOTAL_MEU,
    C.TOTAL_ORIGINAL,
    C.DIFF_TOTAL,
    PADRAO = CASE WHEN ABS(C.DIFF_TOTAL) <= @TOL_VALOR_MENSAL THEN N'REALOCAÇÃO_ENTRE_EVENTOS' ELSE N'DIFERENÇA_TOTAL_CHAPA' END
FROM D_CHAPA C
WHERE C.QTD_EVENTOS_DIVERGENTES > 1
ORDER BY PADRAO DESC, ABS(C.DIFF_TOTAL), C.CODFILIAL, C.CHAPA;
