DECLARE @CODCOLIGADA smallint = 1;
DECLARE @DATA_BASE date = '20260301';
DECLARE @COMPETENCIA date = EOMONTH(@DATA_BASE);
DECLARE @MES int = MONTH(@COMPETENCIA);
DECLARE @ANO int = YEAR(@COMPETENCIA);
DECLARE @PROXIMO_DIA_COMPETENCIA date = DATEADD(day, 1, @COMPETENCIA);

/*
Diagnostico focado nas chaves divergentes de 03/2026.
Objetivo: comparar lado a lado as fontes brutas que podem alimentar SALARIO/JORNADA:
- AIN original
- PFFINANC da competencia
- PFHSTSAL ultimo por evento antes da competencia
- PFHSTSAL ultimo por evento+nrosalario antes da competencia
- PFSALCMP ligada ao NROSALARIO historico
- PFATIVREMUNERADA
*/

;WITH CHAVES AS
(
    SELECT *
    FROM (VALUES
        (1,   '000101085', '0005'),
        (18,  '001800168', '0002'),
        (56,  '005600124', '0003'),
        (66,  '006600690', '0006'),
        (78,  '007800287', '0005'),
        (80,  '008000085', '0006'),
        (100, '010000587', '0004'),
        (112, '011200082', '0003'),
        (121, '012100238', '0005'),
        (123, '012300102', '0002'),
        (125, '012500421', '0002'),
        (148, '014807378', '0005'),
        (150, '015007639', '0003'),
        (167, '016700462', '0219'),
        (169, '016908463', '0200'),
        (169, '016908464', '0200'),
        (169, '016908464', '0207'),
        (169, '016908464', '0210'),
        (180, '018000252', '0002'),
        (62,  '006200022', '0006'),
        (151, '015100033', '0022'),
        (167, '016700301', '0210'),
        (171, '017100115', '0200'),
        (171, '017100115', '0211'),
        (171, '017100115', '0219'),
        (180, '018000252', '0003')
    ) V(CODFILIAL, CHAPA, CODEVENTO)
),
H_EVENTO AS
(
    SELECT
        H.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO
            ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC
        )
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN CHAVES C
      ON C.CHAPA = H.CHAPA
     AND C.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA
      AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
H_SALARIO AS
(
    SELECT
        H.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO, H.NROSALARIO
            ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC
        )
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN CHAVES C
      ON C.CHAPA = H.CHAPA
     AND C.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA
      AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
PS_RN AS
(
    SELECT
        PS.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY PS.CODCOLIGADA, PS.CHAPA, PS.CODEVENTO
            ORDER BY CASE WHEN PS.NROPERIODO = 40 THEN 0 WHEN PS.NROPERIODO = 10 THEN 1 ELSE 2 END,
                     PS.RECMODIFIEDON DESC,
                     PS.RECCREATEDON DESC
        )
    FROM PFFINANC PS WITH (NOLOCK)
    JOIN CHAVES C
      ON C.CHAPA = PS.CHAPA
     AND C.CODEVENTO = PS.CODEVENTO
    WHERE PS.CODCOLIGADA = @CODCOLIGADA
      AND PS.MESCOMP = @MES
      AND PS.ANOCOMP = @ANO
      AND PS.NROPERIODO IN (10, 40)
),
SC_EVENTO AS
(
    SELECT
        SC.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY SC.CODCOLIGADA, SC.CHAPA, SC.CODEVENTO, SC.NROSALARIO
            ORDER BY SC.RECMODIFIEDON DESC, SC.RECCREATEDON DESC
        )
    FROM PFSALCMP SC WITH (NOLOCK)
    JOIN CHAVES C
      ON C.CHAPA = SC.CHAPA
     AND C.CODEVENTO = SC.CODEVENTO
    WHERE SC.CODCOLIGADA = @CODCOLIGADA
      AND SC.RECCREATEDON < @PROXIMO_DIA_COMPETENCIA
),
AR_RN AS
(
    SELECT
        AR.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY AR.CODCOLIGADA, AR.CHAPA, AR.CODEVENTO
            ORDER BY AR.RECMODIFIEDON DESC, AR.RECCREATEDON DESC
        )
    FROM PFATIVREMUNERADA AR WITH (NOLOCK)
    JOIN CHAVES C
      ON C.CHAPA = AR.CHAPA
     AND C.CODEVENTO = AR.CODEVENTO
    WHERE AR.CODCOLIGADA = @CODCOLIGADA
      AND AR.RECMODIFIEDON < @PROXIMO_DIA_COMPETENCIA
)
SELECT
    C.CODFILIAL,
    C.CHAPA,
    PF.NOME,
    PF.CODSITUACAO,
    PF.DATAADMISSAO,
    PF.DATADEMISSAO,
    C.CODEVENTO,
    O_VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.VALOR_HORA AS varchar(50)), ',', '.')),
    O_VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.VALOR_MENSAL AS varchar(50)), ',', '.')),
    O_JORNADA_MENSAL_NUM = TRY_CONVERT(decimal(19,6), REPLACE(CAST(O.JORNADA_MENSAL AS varchar(50)), ',', '.')),

    PS_NROPERIODO = PS.NROPERIODO,
    PS_REF = PS.REF,
    PS_REF_MIN = CAST(ISNULL(PS.REF, 0) * 60 AS decimal(19,4)),
    PS_HORA = PS.HORA,
    PS_VALOR = PS.VALOR,
    PS_VALORORIGINAL = PS.VALORORIGINAL,
    PS_VALOR_ESCOLHIVEL = COALESCE(PS.VALORORIGINAL, PS.VALOR),
    PS_RECCREATEDON = PS.RECCREATEDON,
    PS_RECMODIFIEDON = PS.RECMODIFIEDON,

    H_EVT_NROSALARIO = HE.NROSALARIO,
    H_EVT_DTMUDANCA = HE.DTMUDANCA,
    H_EVT_SALARIO = HE.SALARIO,
    H_EVT_JORNADA = HE.JORNADA,
    H_EVT_VALOR_HORA = CAST(CASE WHEN ISNULL(HE.JORNADA, 0) > 0 THEN HE.SALARIO / (HE.JORNADA / 60.0) ELSE HE.SALARIO END AS decimal(19,6)),
    H_EVT_RECMODIFIEDON = HE.RECMODIFIEDON,

    H_SAL_NROSALARIO = HS.NROSALARIO,
    H_SAL_DTMUDANCA = HS.DTMUDANCA,
    H_SAL_SALARIO = HS.SALARIO,
    H_SAL_JORNADA = HS.JORNADA,
    H_SAL_VALOR_HORA = CAST(CASE WHEN ISNULL(HS.JORNADA, 0) > 0 THEN HS.SALARIO / (HS.JORNADA / 60.0) ELSE HS.SALARIO END AS decimal(19,6)),

    SC_NROSALARIO = SC.NROSALARIO,
    SC_VALOR = SC.VALOR,
    SC_JORNADA = SC.JORNADA,
    SC_VALOR_HORA = CAST(CASE WHEN ISNULL(SC.JORNADA, 0) > 0 THEN SC.VALOR / (SC.JORNADA / 60.0) ELSE SC.VALOR END AS decimal(19,6)),
    SC_RECCREATEDON = SC.RECCREATEDON,
    SC_RECMODIFIEDON = SC.RECMODIFIEDON,

    AR_VALOR = AR.VALOR,
    AR_JORNADA = AR.JORNADA,
    AR_VALOR_HORA = CAST(CASE WHEN ISNULL(AR.JORNADA, 0) > 0 THEN AR.VALOR / (AR.JORNADA / 60.0) ELSE AR.VALOR END AS decimal(19,6)),
    AR_RECCREATEDON = AR.RECCREATEDON,
    AR_RECMODIFIEDON = AR.RECMODIFIEDON,

    PROJECAO_REGRA_MARCO_ATUAL_ENTRARIA = CASE
        WHEN HE.CHAPA IS NOT NULL
         AND SC.RECMODIFIEDON IS NULL
         AND ISNULL(PS.REF, 0) * 60 > ISNULL(HE.JORNADA, 0) THEN 1 ELSE 0 END,
    PROJECAO_REGRA_MARCO_VALOR = CASE
        WHEN HE.CHAPA IS NOT NULL
         AND SC.RECMODIFIEDON IS NULL
         AND ISNULL(PS.REF, 0) * 60 > ISNULL(HE.JORNADA, 0) THEN COALESCE(PS.VALORORIGINAL, PS.VALOR)
        WHEN HE.CHAPA IS NOT NULL THEN HE.SALARIO
        ELSE COALESCE(PS.VALORORIGINAL, PS.VALOR)
    END,
    PROJECAO_REGRA_MARCO_JORNADA = CASE
        WHEN HE.CHAPA IS NOT NULL
         AND SC.RECMODIFIEDON IS NULL
         AND ISNULL(PS.REF, 0) * 60 > ISNULL(HE.JORNADA, 0) THEN PS.REF * 60
        WHEN HE.CHAPA IS NOT NULL THEN HE.JORNADA
        WHEN ISNULL(PS.REF, 0) > 0 THEN PS.REF * 60
        WHEN ISNULL(PS.HORA, 0) > 0 THEN PS.HORA
        WHEN ISNULL(AR.JORNADA, 0) > 0 THEN AR.JORNADA
        ELSE NULL
    END
FROM CHAVES C
LEFT JOIN PFUNC PF WITH (NOLOCK)
  ON PF.CODCOLIGADA = @CODCOLIGADA
 AND PF.CHAPA = C.CHAPA
LEFT JOIN [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] O WITH (NOLOCK)
  ON CAST(O.CODFILIAL AS smallint) = C.CODFILIAL
 AND CAST(O.CHAPA AS varchar(16)) = C.CHAPA
 AND CAST(O.CODEVENTO AS varchar(10)) = C.CODEVENTO
 AND CAST(O.COMPETENCIA AS date) = @COMPETENCIA
LEFT JOIN PS_RN PS
  ON PS.CHAPA = C.CHAPA
 AND PS.CODEVENTO = C.CODEVENTO
 AND PS.RN = 1
LEFT JOIN H_EVENTO HE
  ON HE.CHAPA = C.CHAPA
 AND HE.CODEVENTO = C.CODEVENTO
 AND HE.RN = 1
LEFT JOIN H_SALARIO HS
  ON HS.CHAPA = C.CHAPA
 AND HS.CODEVENTO = C.CODEVENTO
 AND HS.RN = 1
LEFT JOIN SC_EVENTO SC
  ON SC.CHAPA = C.CHAPA
 AND SC.CODEVENTO = C.CODEVENTO
 AND SC.NROSALARIO = COALESCE(HE.NROSALARIO, HS.NROSALARIO, SC.NROSALARIO)
 AND SC.RN = 1
LEFT JOIN AR_RN AR
  ON AR.CHAPA = C.CHAPA
 AND AR.CODEVENTO = C.CODEVENTO
 AND AR.RN = 1
ORDER BY C.CODFILIAL, C.CHAPA, C.CODEVENTO;

/* Resumo para ver se o original bate exatamente com alguma fonte bruta */
;WITH BASE AS
(
    -- Rode primeiro o SELECT acima se quiser ver detalhe. Este bloco e propositalmente simples para edicao manual.
    SELECT 1 AS DUMMY
)
SELECT 'Fim do diagnostico de fontes' AS STATUS;
