/*
Rode este bloco logo depois de popular #MEU_SALARIO_COMPOSTO.
Ele pega dinamicamente TODAS as chaves divergentes e compara as fontes brutas candidatas.
Use WHERE no final para filtrar uma CHAPA/CODEVENTO se a saida ficar grande.
*/

DECLARE @TOL_VALOR_HORA   decimal(19,6) = 0.005;
DECLARE @TOL_VALOR_MENSAL decimal(19,6) = 0.015;

;WITH
MEU AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.')),
        FONTE_DEBUG,
        SALARIO_DEBUG,
        JORNADA_DEBUG
    FROM #MEU_SALARIO_COMPOSTO
),
ORI AS
(
    SELECT
        CODFILIAL = CAST(CODFILIAL AS smallint),
        CHAPA = CAST(CHAPA AS varchar(16)),
        CODEVENTO = CAST(CODEVENTO AS varchar(10)),
        COMPETENCIA = CAST(COMPETENCIA AS date),
        VALOR_HORA = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_HORA AS varchar(50)), ',', '.')),
        VALOR_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(VALOR_MENSAL AS varchar(50)), ',', '.')),
        JORNADA_MENSAL = TRY_CONVERT(decimal(19,6), REPLACE(CAST(JORNADA_MENSAL AS varchar(50)), ',', '.'))
    FROM [GestaoBI].dbo.[AIN_SALARIO_COMPOSTO] WITH (NOLOCK)
    WHERE CAST(COMPETENCIA AS date) = @COMPETENCIA
),
CHAVES AS
(
    SELECT
        CODFILIAL = COALESCE(M.CODFILIAL, O.CODFILIAL),
        CHAPA = COALESCE(M.CHAPA, O.CHAPA),
        CODEVENTO = COALESCE(M.CODEVENTO, O.CODEVENTO),
        COMPETENCIA = COALESCE(M.COMPETENCIA, O.COMPETENCIA),
        M_VALOR_HORA = M.VALOR_HORA,
        O_VALOR_HORA = O.VALOR_HORA,
        M_VALOR_MENSAL = M.VALOR_MENSAL,
        O_VALOR_MENSAL = O.VALOR_MENSAL,
        M_JORNADA_MENSAL = M.JORNADA_MENSAL,
        O_JORNADA_MENSAL = O.JORNADA_MENSAL,
        M.FONTE_DEBUG,
        M.SALARIO_DEBUG,
        M.JORNADA_DEBUG,
        CLASSE = CASE
            WHEN O.CHAPA IS NULL THEN N'SÓ_NO_MEU'
            WHEN M.CHAPA IS NULL THEN N'SÓ_NO_ORIGINAL'
            WHEN ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL
             AND ABS(ISNULL(M.VALOR_HORA,0) - ISNULL(O.VALOR_HORA,0)) <= @TOL_VALOR_HORA THEN N'OK_TOLERANCIA'
            WHEN ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) <= @TOL_VALOR_MENSAL THEN N'MESMO_MENSAL_DIF_VALOR_HORA'
            WHEN ABS(ISNULL(M.VALOR_HORA,0) - ISNULL(O.VALOR_HORA,0)) <= @TOL_VALOR_HORA THEN N'MESMO_VALOR_HORA_DIF_JORNADA'
            ELSE N'VALOR_HORA_E_MENSAL_DIFERENTES'
        END
    FROM MEU M
    FULL OUTER JOIN ORI O
      ON O.CODFILIAL = M.CODFILIAL
     AND O.CHAPA = M.CHAPA
     AND O.CODEVENTO = M.CODEVENTO
     AND O.COMPETENCIA = M.COMPETENCIA
    WHERE O.CHAPA IS NULL
       OR M.CHAPA IS NULL
       OR ABS(ISNULL(M.VALOR_HORA,0) - ISNULL(O.VALOR_HORA,0)) > @TOL_VALOR_HORA
       OR ABS(ISNULL(M.VALOR_MENSAL,0) - ISNULL(O.VALOR_MENSAL,0)) > @TOL_VALOR_MENSAL
),
PS AS
(
    SELECT
        PS.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY PS.CODCOLIGADA, PS.CHAPA, PS.CODEVENTO
            ORDER BY CASE WHEN PS.NROPERIODO = 40 THEN 0 WHEN PS.NROPERIODO = 10 THEN 1 ELSE 2 END,
                     PS.RECMODIFIEDON DESC,
                     PS.RECCREATEDON DESC
        )
    FROM PFFINANC PS WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = PS.CHAPA AND C.CODEVENTO = PS.CODEVENTO
    WHERE PS.CODCOLIGADA = @CODCOLIGADA
      AND PS.MESCOMP = @MES
      AND PS.ANOCOMP = @ANO
      AND PS.NROPERIODO IN (10, 40)
),
H_EVT AS
(
    SELECT
        H.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY H.CODCOLIGADA, H.CHAPA, H.CODEVENTO
            ORDER BY H.DTMUDANCA DESC, H.RECMODIFIEDON DESC, H.RECCREATEDON DESC
        )
    FROM PFHSTSAL H WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = H.CHAPA AND C.CODEVENTO = H.CODEVENTO
    WHERE H.CODCOLIGADA = @CODCOLIGADA
      AND H.DTMUDANCA < @PROXIMO_DIA_COMPETENCIA
),
SC AS
(
    SELECT
        SC.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY SC.CODCOLIGADA, SC.CHAPA, SC.CODEVENTO, SC.NROSALARIO
            ORDER BY SC.RECMODIFIEDON DESC, SC.RECCREATEDON DESC
        )
    FROM PFSALCMP SC WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = SC.CHAPA AND C.CODEVENTO = SC.CODEVENTO
    WHERE SC.CODCOLIGADA = @CODCOLIGADA
      AND SC.RECCREATEDON < @PROXIMO_DIA_COMPETENCIA
),
AR AS
(
    SELECT
        AR.*,
        RN = ROW_NUMBER() OVER
        (
            PARTITION BY AR.CODCOLIGADA, AR.CHAPA, AR.CODEVENTO
            ORDER BY AR.RECMODIFIEDON DESC, AR.RECCREATEDON DESC
        )
    FROM PFATIVREMUNERADA AR WITH (NOLOCK)
    JOIN CHAVES C ON C.CHAPA = AR.CHAPA AND C.CODEVENTO = AR.CODEVENTO
    WHERE AR.CODCOLIGADA = @CODCOLIGADA
      AND AR.RECMODIFIEDON < @PROXIMO_DIA_COMPETENCIA
)
SELECT
    C.CLASSE,
    C.CODFILIAL,
    C.CHAPA,
    PF.NOME,
    PF.CODSITUACAO,
    PF.DATADEMISSAO,
    C.CODEVENTO,
    C.FONTE_DEBUG,
    C.M_VALOR_HORA,
    C.O_VALOR_HORA,
    C.M_VALOR_MENSAL,
    C.O_VALOR_MENSAL,
    DIFF_MENSAL = ISNULL(C.M_VALOR_MENSAL,0) - ISNULL(C.O_VALOR_MENSAL,0),
    C.M_JORNADA_MENSAL,
    C.O_JORNADA_MENSAL,
    C.SALARIO_DEBUG,
    C.JORNADA_DEBUG,

    PS_NROPERIODO = PS.NROPERIODO,
    PS_REF = PS.REF,
    PS_REF_MIN = CAST(ISNULL(PS.REF,0) * 60 AS decimal(19,4)),
    PS_VALOR = PS.VALOR,
    PS_VALORORIGINAL = PS.VALORORIGINAL,
    PS_RECMODIFIEDON = PS.RECMODIFIEDON,

    H_NROSALARIO = H.NROSALARIO,
    H_DTMUDANCA = H.DTMUDANCA,
    H_SALARIO = H.SALARIO,
    H_JORNADA = H.JORNADA,
    H_VALOR_HORA = CAST(CASE WHEN ISNULL(H.JORNADA,0) > 0 THEN H.SALARIO / (H.JORNADA / 60.0) ELSE H.SALARIO END AS decimal(19,6)),
    H_RECMODIFIEDON = H.RECMODIFIEDON,

    SC_NROSALARIO = SC.NROSALARIO,
    SC_VALOR = SC.VALOR,
    SC_JORNADA = SC.JORNADA,
    SC_VALOR_HORA = CAST(CASE WHEN ISNULL(SC.JORNADA,0) > 0 THEN SC.VALOR / (SC.JORNADA / 60.0) ELSE SC.VALOR END AS decimal(19,6)),
    SC_RECCREATEDON = SC.RECCREATEDON,
    SC_RECMODIFIEDON = SC.RECMODIFIEDON,

    AR_VALOR = AR.VALOR,
    AR_JORNADA = AR.JORNADA,
    AR_VALOR_HORA = CAST(CASE WHEN ISNULL(AR.JORNADA,0) > 0 THEN AR.VALOR / (AR.JORNADA / 60.0) ELSE AR.VALOR END AS decimal(19,6)),
    AR_RECMODIFIEDON = AR.RECMODIFIEDON
FROM CHAVES C
LEFT JOIN PFUNC PF WITH (NOLOCK)
  ON PF.CODCOLIGADA = @CODCOLIGADA
 AND PF.CHAPA = C.CHAPA
LEFT JOIN PS
  ON PS.CHAPA = C.CHAPA
 AND PS.CODEVENTO = C.CODEVENTO
 AND PS.RN = 1
LEFT JOIN H_EVT H
  ON H.CHAPA = C.CHAPA
 AND H.CODEVENTO = C.CODEVENTO
 AND H.RN = 1
LEFT JOIN SC
  ON SC.CHAPA = C.CHAPA
 AND SC.CODEVENTO = C.CODEVENTO
 AND SC.NROSALARIO = H.NROSALARIO
 AND SC.RN = 1
LEFT JOIN AR
  ON AR.CHAPA = C.CHAPA
 AND AR.CODEVENTO = C.CODEVENTO
 AND AR.RN = 1
-- WHERE C.CHAPA IN ('003900843','004400324','006500502','016908415')
ORDER BY C.CLASSE, C.CODFILIAL, C.CHAPA, C.CODEVENTO;
